// Public API
export { IdentityAdminClient } from './client.js';

// Error classes
export {
  IdentityApiError,
  NotFoundError,
  ValidationError,
  ConflictError,
  UnauthorizedError,
  ForbiddenError,
  RateLimitError,
  IdentityNetworkError,
} from './errors.js';

// Types
export type {
  AdminClientConfig,
  User,
  Entitlement,
  Membership,
  Organization,
  OidcClient,
  ApiKey,
  Pagination,
  ListUsersParams,
  CreateUserData,
  UpdateUserData,
  ListEntitlementsParams,
  GrantEntitlementData,
  ListMembershipsParams,
  AddMembershipData,
  ListOrganizationsParams,
  CreateOrganizationData,
  UpdateOrganizationData,
  ListClientsParams,
  RegisterClientData,
  UpdateClientData,
  ListApiKeysParams,
  CreateApiKeyData,
  UpdateApiKeyData,
  ListUsersResponse,
  UserResponse,
  DeleteUserResponse,
  ListEntitlementsResponse,
  EntitlementResponse,
  ListMembershipsResponse,
  MembershipResponse,
  ListOrganizationsResponse,
  OrganizationResponse,
  ListClientsResponse,
  ClientResponse,
  ClientWithSecretResponse,
  ListApiKeysResponse,
  ApiKeyResponse,
  ApiKeyWithKeyResponse,
  ApiKeyRevokeResponse,
  ApiKeyScopesResponse,
  IdentityErrorResponse,
} from './types.js';
